<?php 
use Magento\Framework\App\Action\Action;
if($this->getConfig('enabled')){ ?>
	<?php $_productCollection = $this->getProducts();
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	?>
	<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
	<?php else: ?>
	    <?php
	        $viewMode = 'grid';
	        $image = 'category_page_grid_m';
	        $showDescription = false;
	        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	   /*Grid*/
			/**
			 * Position for actions regarding image size changing in vde if needed
			 */
			$pos = $block->getPositioned();
		?>
	    <div class="rokan-mostviewed">
			<div class="rokan-product-heading rokan-mostviewed-heading"><h2><?php echo $this->getConfig('title')?></h2></div>
	        <?php $iterator = 1; 
				$i = 0;
				$rows = 3; ?>
	        <ul class="owl">
	            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
	            <?php foreach ($_productCollection as $_product): ?>
					<?php if($i++ %$rows == 0) echo "<li class='item mostviewed-item'>"; ?>
	                <div class="product-item" data-container="product-grid">
	                    <?php
	                    $productImage = $block->getImage($_product, $image);
	                    if ($pos != null) {
	                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
	                            . 'top:' . $productImage->getHeight() . 'px;"';
	                    }
	                    ?>
						<div class="product-photo pull-left">
							<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1-m');?>
								<span class="image0 image-switch">
									<?php echo $productImage->toHtml(); ?>
								</span>
								<span class="image1 image-switch">
									<?php echo $productImageThumb->toHtml(); ?>
								</span>
							</a>
						</div>
	                    <div class="product-info">
							<?php
								$_productNameStripped = $block->stripTags($_product->getName(), null, true);
							?>
							<h3 class="product-name">
								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
									<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</h3>
							<div class="product-ratting">
								<?php echo $block->getProductDetailsHtml($_product); ?>
							</div>
							<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
							<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
							
	                        <div class="addto-links-icons visible-onhover">
	                            <div class="action-inner product-item-actions"<?php if($pos) {echo strpos($pos, $viewMode . '-actions') ? $position : '';}  ?>>
	                             
	                            </div>
	                            <?php if ($showDescription):?>
	                                <div class="product description product-item-description">
	                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
	                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
	                                       class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
	                                </div>
	                            <?php endif; ?>
	                        </div>
	                    </div>
	                </div>
	                <?php if($i == $rows || $i == count($_productCollection)) echo '</li>'; ?>
	            <?php endforeach; ?>
	        </ul>
	    </div>
	    <?php if (!$block->isRedirectToCartEnabled()) : ?>
	        <script type="text/x-magento-init">
	        {
	            "[data-role=tocart-form], .form.map.checkout": {
	                "catalogAddToCart": {}
	            }
	        }
	        </script>
			
	    <?php endif; ?>
		<script type="text/javascript">
			require([
				'jquery',
				'mage/mage',
				'rokanthemes/owl'
			], function ($) {
				'use strict';

				jQuery(".rokan-mostviewed .owl").owlCarousel({
					lazyLoad: true,
					autoPlay : false,
					items : 1,
					itemsDesktop : [1199,1],
					itemsDesktopSmall : [980,1],
					itemsTablet: [768,1],
					itemsMobile : [479,1],
					slideSpeed : 500,
					paginationSpeed : 500,
					rewindSpeed : 500,
					navigation : true,
					stopOnHover : true,
					pagination :false,
					scrollPerPage:true,
				});
			});
		</script>
	<?php endif; ?>
 
<?php } ?>